spring:
  application:
    name: webflux
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/Demo
  datasource:
    url: jdbc:h2:mem:SBanco;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      schema: PUBLIC
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: PUBLIC
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  keycloak:
    realm: Demo
    auth-server-url: http://localhost:8081
    resource: meu-app
    credentials:
      secret: Ckj7r9tlbV7KpyK5QAjok2C4f46Uanpf
    use-resource-role-mappings: true

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force-response: true